/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import utilerias.AsignaIcon;

/**
 *
 * @author Julian
 */
public class Menu extends JFrame {
    private AsignaIcon asignaicon;
    private ButtonGroup grupoBtn, grupoBtnAlum ;
    private JList listagrupos,listagrado1,listagrado2,listagrado3;


    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);
        
        ((javax.swing.plaf.basic.BasicInternalFrameUI)jInternalFrame1.getUI()).setNorthPane(null);
        jInternalFrame1.getContentPane().setBackground(new Color(84,14,28));
        
        listagrupos = new JList();        
        listagrado1 = new JList();        
        listagrado2 = new JList();        
        listagrado3 = new JList();

        listagrupos.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(listagrupos.getSelectedIndex()==0){
                listagrado1.setFont(new Font("Segoe UI", 0, 15)); // NOI18N
        listagrado1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Grupo A", "Grupo B", "Grupo C" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JScrollPane scrollLista1 = new JScrollPane();
        scrollLista1.setBounds(0, 0,90, 90);
        scrollLista1.setViewportView(listagrupos);
        jPanel1.add(scrollLista1);
                }
                else if(listagrupos.getSelectedIndex()==1){
                 System.out.println("2");
                }
                else 
                    System.out.println("3");
            }
        });
        
        asignaicon = new AsignaIcon();
        etiClose.setIcon(asignaicon.crearIcono("src/imagenes/btnClose.png", etiClose));
        etiRest.setIcon(asignaicon.crearIcono("src/imagenes/rest.png", etiRest));
        etimin.setIcon(asignaicon.crearIcono("src/imagenes/mini.png", etimin));

        grupoBtn = new ButtonGroup();
        grupoBtn.add(jRadioButton3);
        grupoBtn.add(jRadioButton4);
        grupoBtnAlum = new ButtonGroup();
        grupoBtnAlum.add(jRadioButton5);
        grupoBtnAlum.add(jRadioButton6);
        
        etiid.setEnabled(false);
        txtid.setEnabled(false);
        
        eticode.setVisible(false);
        cbxcode.setVisible(false);
        eticode1.setVisible(false);
        cbxcode1.setVisible(false);
            
        listaGrupoA.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                
        listaGrupos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        etiClose = new javax.swing.JLabel();
        etiRest = new javax.swing.JLabel();
        etimin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        etiid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        etiLogin1 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        txtnameReg = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        txtApePReg = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txtApeMReg = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        txtDirReg = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        txtTelReg = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        txtTelEmerReg = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        etiAgrupos = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        cbxGrupos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaGrupos = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaGrupoA = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        eticode = new javax.swing.JLabel();
        cbxcode = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        txtnameReg1 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        txtApePReg1 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txtApeMReg1 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        txtDirReg1 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        txtTelReg1 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtTelEmerReg1 = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cbxtutor = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        eticode1 = new javax.swing.JLabel();
        cbxcode1 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(161, 42, 67));

        etiClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiCloseMouseExited(evt);
            }
        });

        etiRest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiRestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiRestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiRestMouseExited(evt);
            }
        });

        etimin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiminMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(149, 152, 154));
        jLabel2.setText("Autenticacion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 588, Short.MAX_VALUE)
                .addComponent(etimin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiRest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(etimin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiRest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        jTabbedPane1.setBackground(new java.awt.Color(84, 14, 28));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(84, 14, 28));
        jPanel1.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Opcion");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 11, 44, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Sexo", "Tipo Sanguineo", "Tutor", "Direccion", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(160, 20, 570, 500);

        etiid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiid.setForeground(new java.awt.Color(255, 255, 255));
        etiid.setText("ID Alumno");
        jPanel1.add(etiid);
        etiid.setBounds(10, 300, 80, 20);

        txtid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtidMouseClicked(evt);
            }
        });
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });
        jPanel1.add(txtid);
        txtid.setBounds(10, 320, 120, 20);

        jCheckBox1.setBackground(new java.awt.Color(84, 14, 28));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Busqueda por :");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(10, 270, 120, 29);

        jButton6.setText("Buscar");
        jPanel1.add(jButton6);
        jButton6.setBounds(40, 360, 90, 30);

        etiLogin1.setBackground(new java.awt.Color(255, 255, 255));
        etiLogin1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiLogin1.setText("Detalles      >");
        etiLogin1.setOpaque(true);
        etiLogin1.setPreferredSize(new java.awt.Dimension(200, 32));
        etiLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiLogin1MouseClicked(evt);
            }
        });
        jPanel1.add(etiLogin1);
        etiLogin1.setBounds(40, 410, 90, 30);

        jComboBox8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grupos", "Maestros", " " }));
        jComboBox8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox8ItemStateChanged(evt);
            }
        });
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox8);
        jComboBox8.setBounds(10, 41, 120, 26);

        jInternalFrame1.setBackground(new java.awt.Color(84, 14, 28));
        jInternalFrame1.setBorder(null);
        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jInternalFrame1.setVisible(true);

        jMenu1.setText("Grados");

        jMenu3.setText("Grado 1");

        jMenuItem1.setText("Grupo A");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem7.setText("Grupo B");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem2.setText("Grupo C");
        jMenu3.add(jMenuItem2);

        jMenuItem8.setText("Grupo D");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Grupo E");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Grupo F");
        jMenu3.add(jMenuItem10);

        jMenu1.add(jMenu3);

        jMenu4.setText("Grado 2");

        jMenuItem11.setText("Grupo A");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem12.setText("Grupo B");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuItem13.setText("Grupo C");
        jMenu4.add(jMenuItem13);

        jMenuItem14.setText("Grupo D");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuItem15.setText("Grupo E");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuItem16.setText("Grupo F");
        jMenu4.add(jMenuItem16);

        jMenu1.add(jMenu4);

        jMenu5.setText("Grado 3");

        jMenuItem17.setText("Grupo A");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuItem18.setText("Grupo B");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem18);

        jMenuItem19.setText("Grupo C");
        jMenu5.add(jMenuItem19);

        jMenuItem20.setText("Grupo D");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem20);

        jMenuItem21.setText("Grupo E");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem21);

        jMenuItem22.setText("Grupo F");
        jMenu5.add(jMenuItem22);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jInternalFrame1);
        jInternalFrame1.setBounds(10, 80, 130, 30);

        jTabbedPane1.addTab("Consulta", jPanel1);

        jPanel3.setBackground(new java.awt.Color(84, 14, 28));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Nombre");
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 151, -1));

        txtnameReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnameRegMouseClicked(evt);
            }
        });
        txtnameReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameRegActionPerformed(evt);
            }
        });
        txtnameReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnameRegKeyTyped(evt);
            }
        });
        jPanel3.add(txtnameReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Apellido Paterno");
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 151, -1));

        txtApePReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApePRegMouseClicked(evt);
            }
        });
        txtApePReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApePRegActionPerformed(evt);
            }
        });
        txtApePReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApePRegKeyTyped(evt);
            }
        });
        jPanel3.add(txtApePReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 200, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Apellido Materno");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 151, -1));

        txtApeMReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApeMRegMouseClicked(evt);
            }
        });
        txtApeMReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApeMRegActionPerformed(evt);
            }
        });
        txtApeMReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeMRegKeyTyped(evt);
            }
        });
        jPanel3.add(txtApeMReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 200, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Ocupacion");
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 151, 30));

        txtDirReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDirRegMouseClicked(evt);
            }
        });
        txtDirReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirRegActionPerformed(evt);
            }
        });
        jPanel3.add(txtDirReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Correo");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 151, 30));
        jPanel3.add(txtTelReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 200, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Numero de Telefono ");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 151, 30));

        txtTelEmerReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelEmerRegKeyTyped(evt);
            }
        });
        jPanel3.add(txtTelEmerReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 200, -1));

        jRadioButton3.setText("M");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        etiAgrupos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiAgrupos.setForeground(new java.awt.Color(255, 255, 255));
        etiAgrupos.setText("Agregar Materias");
        jPanel3.add(etiAgrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 120, -1));

        jRadioButton4.setText("F");
        jRadioButton4.setBorderPainted(true);
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 20));

        cbxGrupos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxGrupos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primer Año", "Segundo Año", "Tercer Año" }));
        cbxGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGruposActionPerformed(evt);
            }
        });
        jPanel3.add(cbxGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, -1, -1));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));

        listaGrupos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Matematicas", "Español", "Quimiica", "Civica", "Artes", "Lectura y Redaccion" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaGrupos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 200, 100));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sexo");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Materias Asignados");
        jLabel15.setToolTipText("");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        listaGrupoA.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "MAtematicas", "Ciencias Naturales", "Quimica", "Artes", "Civica", "Español", "Lectura y Redaccion" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaGrupoA);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 200, 150));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Opcion");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jComboBox5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar", "Actualizar", "Baja" }));
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, -1));

        eticode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eticode.setForeground(new java.awt.Color(255, 255, 255));
        eticode.setText("Codigo");
        jPanel3.add(eticode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cbxcode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "511165", "68546541", "65146", "651651" }));
        cbxcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcodeActionPerformed(evt);
            }
        });
        jPanel3.add(cbxcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, -1));

        jButton5.setText("Agregar");
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        jTabbedPane1.addTab("Gestion Profesor", jPanel3);

        jPanel4.setBackground(new java.awt.Color(84, 14, 28));

        jPanel6.setBackground(new java.awt.Color(84, 14, 28));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Nombre");
        jPanel6.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 151, -1));

        txtnameReg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnameReg1MouseClicked(evt);
            }
        });
        txtnameReg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameReg1ActionPerformed(evt);
            }
        });
        txtnameReg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnameReg1KeyTyped(evt);
            }
        });
        jPanel6.add(txtnameReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Apellido Paterno");
        jPanel6.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 151, -1));

        txtApePReg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApePReg1MouseClicked(evt);
            }
        });
        txtApePReg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApePReg1ActionPerformed(evt);
            }
        });
        txtApePReg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApePReg1KeyTyped(evt);
            }
        });
        jPanel6.add(txtApePReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 200, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Apellido Materno");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 151, -1));

        txtApeMReg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApeMReg1MouseClicked(evt);
            }
        });
        txtApeMReg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApeMReg1ActionPerformed(evt);
            }
        });
        txtApeMReg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeMReg1KeyTyped(evt);
            }
        });
        jPanel6.add(txtApeMReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 200, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Direccion");
        jPanel6.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 151, 30));

        txtDirReg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDirReg1MouseClicked(evt);
            }
        });
        txtDirReg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirReg1ActionPerformed(evt);
            }
        });
        jPanel6.add(txtDirReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Tipo de Sangre");
        jPanel6.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 151, 30));

        txtTelReg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelReg1KeyTyped(evt);
            }
        });
        jPanel6.add(txtTelReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 200, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Numero de Emergencia ");
        jPanel6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 151, 30));

        txtTelEmerReg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelEmerReg1KeyTyped(evt);
            }
        });
        jPanel6.add(txtTelEmerReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 200, -1));

        jRadioButton5.setText("M");
        jRadioButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton5MouseClicked(evt);
            }
        });
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jRadioButton6.setText("F");
        jRadioButton6.setBorderPainted(true);
        jRadioButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton6MouseClicked(evt);
            }
        });
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tutor");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, -1, -1));

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Sexo");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        cbxtutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxtutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "445654" }));
        cbxtutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtutorActionPerformed(evt);
            }
        });
        jPanel6.add(cbxtutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 120, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Opcion");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jComboBox7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar", "Actualizar", "Baja" }));
        jComboBox7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox7ItemStateChanged(evt);
            }
        });
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, -1));

        eticode1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eticode1.setForeground(new java.awt.Color(255, 255, 255));
        eticode1.setText("Codigo");
        jPanel6.add(eticode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cbxcode1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxcode1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "511165", "68546541", "65146", "651651" }));
        cbxcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcode1ActionPerformed(evt);
            }
        });
        jPanel6.add(cbxcode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Gestion Alumno", jPanel4);

        jPanel5.setBackground(new java.awt.Color(84, 14, 28));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gestion Materia", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 760, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etiCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseClicked
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
            "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        dispose();
        Sii sii = new Sii();
        sii.setVisible(true);
        
        }
    }//GEN-LAST:event_etiCloseMouseClicked

    private void etiCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseEntered
        etiClose.setIcon(asignaicon.crearIcono("src/imagenes/btnClose2.png", etiClose));
    }//GEN-LAST:event_etiCloseMouseEntered

    private void etiCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseExited
        etiClose.setIcon(asignaicon.crearIcono("src/imagenes/btnClose.png", etiClose));
    }//GEN-LAST:event_etiCloseMouseExited

    private void etiRestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseClicked
        /*if(getExtendedState() == JFrame.MAXIMIZED_BOTH){//1
            setExtendedState(JFrame.NORMAL);//2
        }else
        setExtendedState(JFrame.MAXIMIZED_BOTH);//3*/
    }//GEN-LAST:event_etiRestMouseClicked

    private void etiRestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseEntered
        etiRest.setIcon(asignaicon.crearIcono("src/imagenes/rest2.png", etiRest));
    }//GEN-LAST:event_etiRestMouseEntered

    private void etiRestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseExited
        etiRest.setIcon(asignaicon.crearIcono("src/imagenes/rest.png", etiRest));
    }//GEN-LAST:event_etiRestMouseExited

    private void etiminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseClicked
        setExtendedState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_etiminMouseClicked

    private void etiminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseEntered
        etimin.setIcon(asignaicon.crearIcono("src/imagenes/mini2.png", etimin));
    }//GEN-LAST:event_etiminMouseEntered

    private void etiminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseExited
        etimin.setIcon(asignaicon.crearIcono("src/imagenes/mini.png", etimin));
    }//GEN-LAST:event_etiminMouseExited

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void txtnameRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameRegMouseClicked
        JTextField j = new JTextField();
        txtnameReg.setBorder(j.getBorder());
    }//GEN-LAST:event_txtnameRegMouseClicked

    private void txtnameRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameRegActionPerformed

    }//GEN-LAST:event_txtnameRegActionPerformed

    private void txtnameRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameRegKeyTyped
        restriccionLetra(evt);
    }//GEN-LAST:event_txtnameRegKeyTyped

    private void txtApePRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApePRegMouseClicked
        JTextField j = new JTextField();
        txtApePReg.setBorder(j.getBorder());
    }//GEN-LAST:event_txtApePRegMouseClicked

    private void txtApePRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApePRegActionPerformed

    }//GEN-LAST:event_txtApePRegActionPerformed

    private void txtApePRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApePRegKeyTyped
        restriccionLetra(evt);
    }//GEN-LAST:event_txtApePRegKeyTyped

    private void txtApeMRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApeMRegMouseClicked
        JTextField j = new JTextField();
        txtApeMReg.setBorder(j.getBorder());
    }//GEN-LAST:event_txtApeMRegMouseClicked

    private void txtApeMRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApeMRegActionPerformed

    }//GEN-LAST:event_txtApeMRegActionPerformed

    private void txtApeMRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeMRegKeyTyped
        restriccionLetra(evt);
    }//GEN-LAST:event_txtApeMRegKeyTyped

    private void txtDirRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDirRegMouseClicked
        JTextField j = new JTextField();
        txtDirReg.setBorder(j.getBorder());
        
    }//GEN-LAST:event_txtDirRegMouseClicked

    private void txtDirRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirRegActionPerformed

    }//GEN-LAST:event_txtDirRegActionPerformed

    private void txtTelEmerRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelEmerRegKeyTyped
        restriccionNum(evt);
    }//GEN-LAST:event_txtTelEmerRegKeyTyped

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        JRadioButton j = new JRadioButton();
        jRadioButton3.setBorder(j.getBorder());
        jRadioButton4.setBorder(j.getBorder());
        //jRadioButton3.setBorderPainted(false); jRadioButton4.setBorderPainted(false);
    }//GEN-LAST:event_jRadioButton3MouseClicked

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseClicked
        jRadioButton3MouseClicked(null);
    }//GEN-LAST:event_jRadioButton4MouseClicked

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtnameReg.setText("");
        txtApePReg.setText("");
        txtApeMReg.setText("");
        txtDirReg.setText("");
        txtTelReg.setText("");
        txtTelEmerReg.setText("");
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        cbxGrupos.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void cbxcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxcodeActionPerformed

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
       if(evt.getItem().equals("Registrar")){
        eticode.setVisible(false);
        cbxcode.setVisible(false);
        etiAgrupos.setVisible(true);
        cbxGrupos.setVisible(true);
        jScrollPane1.setVisible(true);
        txtnameReg.setEnabled(true);
        txtApePReg.setEnabled(true);
        txtApeMReg.setEnabled(true);
        txtDirReg.setEnabled(true);
        txtTelReg.setEnabled(true);
        txtTelEmerReg.setEnabled(true);
        jRadioButton3.setEnabled(true);
        jRadioButton4.setEnabled(true);
        cbxtutor.setEnabled(true);
       }
       else if (evt.getItem().equals("Actualizar")){
        eticode.setVisible(true);
        cbxcode.setVisible(true);
        etiAgrupos.setVisible(true);
        cbxGrupos.setVisible(true);
        jScrollPane1.setVisible(true);
        txtnameReg.setEnabled(true);
        txtApePReg.setEnabled(true);
        txtApeMReg.setEnabled(true);
        txtDirReg.setEnabled(true);
        txtTelReg.setEnabled(true);
        txtTelEmerReg.setEnabled(true);
        jRadioButton3.setEnabled(true);
        jRadioButton4.setEnabled(true);
       }
       else{
        eticode.setVisible(true);
        cbxcode.setVisible(true);
        etiAgrupos.setVisible(false);
        cbxGrupos.setVisible(false);
        jScrollPane1.setVisible(false);
        txtnameReg.setEnabled(false);
        txtApePReg.setEnabled(false);
        txtApeMReg.setEnabled(false);
        txtDirReg.setEnabled(false);
        txtTelReg.setEnabled(false);
        txtTelEmerReg.setEnabled(false);
        jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
       }
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void txtnameReg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameReg1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameReg1MouseClicked

    private void txtnameReg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameReg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameReg1ActionPerformed

    private void txtnameReg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameReg1KeyTyped
restriccionLetra(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameReg1KeyTyped

    private void txtApePReg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApePReg1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApePReg1MouseClicked

    private void txtApePReg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApePReg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApePReg1ActionPerformed

    private void txtApePReg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApePReg1KeyTyped
restriccionLetra(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtApePReg1KeyTyped

    private void txtApeMReg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApeMReg1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApeMReg1MouseClicked

    private void txtApeMReg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApeMReg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApeMReg1ActionPerformed

    private void txtApeMReg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeMReg1KeyTyped
restriccionLetra(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtApeMReg1KeyTyped

    private void txtDirReg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDirReg1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirReg1MouseClicked

    private void txtDirReg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirReg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirReg1ActionPerformed

    private void txtTelReg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelReg1KeyTyped
restriccionLetra(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelReg1KeyTyped

    private void txtTelEmerReg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelEmerReg1KeyTyped
restriccionNum(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelEmerReg1KeyTyped

    private void jRadioButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5MouseClicked

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6MouseClicked

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbxtutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxtutorActionPerformed

    private void jComboBox7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox7ItemStateChanged
        if(evt.getItem().equals("Registrar")){
        eticode1.setVisible(false);
        cbxcode1.setVisible(false);
        txtnameReg1.setEnabled(true);
        txtApePReg1.setEnabled(true);
        txtApeMReg1.setEnabled(true);
        txtDirReg1.setEnabled(true);
        txtTelReg1.setEnabled(true);
        txtTelEmerReg1.setEnabled(true);
        jRadioButton5.setEnabled(true);
        jRadioButton6.setEnabled(true);
        cbxtutor.setEnabled(true);
       }
        else if (evt.getItem().equals("Actualizar")){
        eticode1.setVisible(true);
        cbxcode1.setVisible(true);
        txtnameReg1.setEnabled(true);
        txtApePReg1.setEnabled(true);
        txtApeMReg1.setEnabled(true);
        txtDirReg1.setEnabled(true);
        txtTelReg1.setEnabled(true);
        txtTelEmerReg1.setEnabled(true);
        jRadioButton5.setEnabled(true);
        jRadioButton6.setEnabled(true);
        cbxtutor.setEnabled(true);

       }
       else{
        eticode1.setVisible(true);
        cbxcode1.setVisible(true);
        txtnameReg1.setEnabled(false);
        txtApePReg1.setEnabled(false);
        txtApeMReg1.setEnabled(false);
        txtDirReg1.setEnabled(false);
        txtTelReg1.setEnabled(false);
        txtTelEmerReg1.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton6.setEnabled(false);
        cbxtutor.setEnabled(false);


        
       }
    }//GEN-LAST:event_jComboBox7ItemStateChanged

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void cbxcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxcode1ActionPerformed

    private void txtidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidMouseClicked

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyTyped

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        if(jCheckBox1.isSelected()){
            etiid.setEnabled(true);
            txtid.setEnabled(true);
        }else{
            etiid.setEnabled(false);
            txtid.setEnabled(false);
        }
            
            
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void etiLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLogin1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_etiLogin1MouseClicked

    private void jComboBox8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox8ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ItemStateChanged

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void cbxGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGruposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGruposActionPerformed
 public void restriccionLetra(java.awt.event.KeyEvent evt){
        char c=evt.getKeyChar(); 
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
              JOptionPane.showMessageDialog(null, "Ingresa Solo Letras");
          } 
    }
    
    public void restriccionNum(java.awt.event.KeyEvent evt){
    char c=evt.getKeyChar(); 
          if(Character.isLetter(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
              JOptionPane.showMessageDialog(null, "Ingresa Solo Numeros");
          } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxGrupos;
    private javax.swing.JComboBox<String> cbxcode;
    private javax.swing.JComboBox<String> cbxcode1;
    private javax.swing.JComboBox<String> cbxtutor;
    private javax.swing.JLabel etiAgrupos;
    private javax.swing.JLabel etiClose;
    private javax.swing.JLabel etiLogin1;
    private javax.swing.JLabel etiRest;
    private javax.swing.JLabel eticode;
    private javax.swing.JLabel eticode1;
    private javax.swing.JLabel etiid;
    private javax.swing.JLabel etimin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> listaGrupoA;
    private javax.swing.JList<String> listaGrupos;
    private javax.swing.JTextField txtApeMReg;
    private javax.swing.JTextField txtApeMReg1;
    private javax.swing.JTextField txtApePReg;
    private javax.swing.JTextField txtApePReg1;
    private javax.swing.JTextField txtDirReg;
    private javax.swing.JTextField txtDirReg1;
    private javax.swing.JTextField txtTelEmerReg;
    private javax.swing.JTextField txtTelEmerReg1;
    private javax.swing.JTextField txtTelReg;
    private javax.swing.JTextField txtTelReg1;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnameReg;
    private javax.swing.JTextField txtnameReg1;
    // End of variables declaration//GEN-END:variables
}
