/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import utilerias.AsignaIcon;
import java.awt.Font;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author Julian
 */
public class Sii extends JFrame {
    private AsignaIcon asignaicon;
    private JList listaLogin;

    /**
     * Creates new form Sii
     */
    public Sii() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);
        
        listaLogin = new JList<>();
        listaLogin.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(listaLogin.getSelectedIndex()==0){
                 dispose();
                 Menu menu = new Menu();
                 menu.setVisible(true);
                }
                else if(listaLogin.getSelectedIndex()==1)
                    System.out.println("secre");
                    else
                    System.out.println("profe");
                    
            }
        });
        
        asignaicon = new AsignaIcon();
        etiLogo.setIcon(asignaicon.crearIcono("src/imagenes/logo.png", etiLogo));
        etiClose.setIcon(asignaicon.crearIcono("src/imagenes/btnClose.png", etiClose));
        etiRest.setIcon(asignaicon.crearIcono("src/imagenes/rest.png", etiRest));
        etimin.setIcon(asignaicon.crearIcono("src/imagenes/mini.png", etimin));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        etiLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        etiLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        etiClose = new javax.swing.JLabel();
        etiRest = new javax.swing.JLabel();
        etimin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(817, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(84, 14, 28));
        jPanel1.setPreferredSize(new java.awt.Dimension(752, 486));

        txtcode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcode.setPreferredSize(new java.awt.Dimension(406, 50));
        txtcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        txtpass.setPreferredSize(new java.awt.Dimension(406, 50));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });

        etiLogin.setBackground(new java.awt.Color(255, 255, 255));
        etiLogin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        etiLogin.setText("Ingresar                      >");
        etiLogin.setOpaque(true);
        etiLogin.setPreferredSize(new java.awt.Dimension(200, 32));
        etiLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(txtcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(etiLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(etiLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 760, 440));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(149, 152, 154));
        jLabel1.setText("Sistema Integral de Información");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));
        getContentPane().add(etiLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 120));

        jPanel2.setBackground(new java.awt.Color(161, 42, 67));

        etiClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiCloseMouseExited(evt);
            }
        });

        etiRest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiRestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiRestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiRestMouseExited(evt);
            }
        });

        etimin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiminMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(149, 152, 154));
        jLabel2.setText("Autenticacion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 588, Short.MAX_VALUE)
                .addComponent(etimin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiRest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(etimin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiRest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etiCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseClicked
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
            "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_etiCloseMouseClicked

    private void etiCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseEntered
        etiClose.setIcon(asignaicon.crearIcono("src/imagenes/btnClose2.png", etiClose));
    }//GEN-LAST:event_etiCloseMouseEntered

    private void etiCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCloseMouseExited
        etiClose.setIcon(asignaicon.crearIcono("src/imagenes/btnClose.png", etiClose));
    }//GEN-LAST:event_etiCloseMouseExited

    private void etiRestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseClicked
        /*if(getExtendedState() == JFrame.MAXIMIZED_BOTH){//1
            setExtendedState(JFrame.NORMAL);//2
        }else
        setExtendedState(JFrame.MAXIMIZED_BOTH);//3*/
    }//GEN-LAST:event_etiRestMouseClicked

    private void etiRestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseEntered
        etiRest.setIcon(asignaicon.crearIcono("src/imagenes/rest2.png", etiRest));
    }//GEN-LAST:event_etiRestMouseEntered

    private void etiRestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRestMouseExited
        etiRest.setIcon(asignaicon.crearIcono("src/imagenes/rest.png", etiRest));
    }//GEN-LAST:event_etiRestMouseExited

    private void etiminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseClicked
        setExtendedState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_etiminMouseClicked

    private void etiminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseEntered
        etimin.setIcon(asignaicon.crearIcono("src/imagenes/mini2.png", etimin));
    }//GEN-LAST:event_etiminMouseEntered

    private void etiminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiminMouseExited
        etimin.setIcon(asignaicon.crearIcono("src/imagenes/mini.png", etimin));
    }//GEN-LAST:event_etiminMouseExited

    private void txtcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodeActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void etiLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLoginMouseClicked
       listaLogin.setFont(new Font("Segoe UI", 0, 15)); // NOI18N
        listaLogin.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Administrador", "Secretaria", "Profesor" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JScrollPane scrollLista = new JScrollPane();
        scrollLista.setBounds(440, 278,220, 90);
        scrollLista.setViewportView(listaLogin);
        jPanel1.add(scrollLista);
    }//GEN-LAST:event_etiLoginMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sii().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiClose;
    private javax.swing.JLabel etiLogin;
    private javax.swing.JLabel etiLogo;
    private javax.swing.JLabel etiRest;
    private javax.swing.JLabel etimin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtcode;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
